- ec2_vpc_net_facts:
    filters:
      "tag:Role": "{{ role.tag }}"
  register: vpc_facts

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"

- ec2_group_facts:
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Role": "{{ role.tag }}"
  register: sec_groups

- name: delete VPC security groups
  ec2_group:
    state: absent
    name: "{{ item.group_name }}"
    group_id: "{{ item.group_id }}"
    vpc_id: "{{ vpc_id }}"
  loop: "{{ sec_groups.security_groups }}"