- name: create VPC subnets
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.value.cidr }}"
    az: "{{ item.value.az }}"
    tags:
      Name: "{{ item.key }}"
      Role: "{{ role.tag }}"
  with_dict: "{{ subnets }}"
  register: vpc_subnets