- ec2_vpc_net_facts:
    filters:
      "tag:Role": "{{ role.tag }}"
  register: vpc_facts

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"


- ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "{{ role.tag }}-igw"
      Role: "{{ role.tag }}"
    state: present
  register: igw