- ec2_vpc_net_facts:
    filters:
      "tag:Role": "{{ role.tag }}"
  register: vpc_facts

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"

- ec2_group_facts:
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Role": "{{ role.tag }}"
  register: sec_groups_facts

- ec2_vpc_subnet_facts:
    filters:
      "tag:Role": "{{ role.tag }}"
  register: subnets_facts

- iam_role_facts:
    name: "{{ eks_cluster_role_name }}"
  register: iam_role_facts

- name: ensure EKS cluster exists
  aws_eks_cluster:
    state: present
    name: "{{ eks_cluster_name }}"
    version: "{{ kube_version }}"
    security_groups: "{{ sec_groups_facts.security_groups | json_query('[].group_name') }}"
    subnets: "{{ subnets_facts.subnets | json_query('[].id') }}"
    role_arn: "{{ iam_role_facts.iam_roles[0].arn }}"
    region: "{{ vpc.region }}"
    wait: yes
  register: eks_create

- iam_role_facts:
    name: "{{ eks_worker_role_name }}"
  register: worker_role_facts

- debug:
    msg: "{{ worker_role_facts.iam_roles[0].arn }}"

- name: "set fact: VPC ID"
  set_fact:
    eks_worker_iam_role_arn: "{{ worker_role_facts.iam_roles[0].arn }}"

- name: output kube config
  template:
    src: kube.config.j2
    dest: "{{ eks_kubeconfig }}"

- name: install cache helper script
  copy:
    src: aws-iam-authenticator-with-cache
    dest: "{{ eks_kubeconfig | dirname }}/aws-iam-authenticator-with-cache"
    mode: 0755

#- name: add authentication configuration
#  k8s:
#    definition: "{{ lookup('template', role_path + '/templates/aws-auth-cm.yml') }}"
#    kubeconfig: "{{ eks_kubeconfig }}"