- name: create VPC
  ec2_vpc_net:
    state: present
    name: "{{ vpc.name }}"
    cidr_block: "{{ vpc.cidr }}"
    region: "{{ vpc.region }}"
    tags:
      Name: "{{ role.tag }}-vpc"
      Role: "{{ role.tag }}"
  register: create_vpc

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ create_vpc.vpc.id }}"