kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: "http-server"
  selector:
    app: guestbook
    tier: frontend
  type: LoadBalancer