- ec2_vpc_net_facts:
    filters:
      "tag:Role": "{{ role.tag }}"
  register: vpc_facts

- name: "set fact: VPC ID"
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"

- name: Gather facts about a filtered list of Internet Gateways
  ec2_vpc_route_table_facts:
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Role": "{{ role.tag }}"
  register: rt_facts

- name: delete route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc.region }}"
    route_table_id: "{{ item.id }}"
    lookup: id
    state: absent
  loop: "{{ rt_facts.route_tables }}"